version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: sudo pip install pipenv virtualenv
      - run: pipenv --three install --dev
      - run: pipenv run pytest --version
