version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          command: |
            sudo pip install pipenv virtualenv
            python --version
            pipenv --version
            pipenv install
            pipenv run pytest --version
