version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: echo 'export PATH=/home/circleci/.local/bin/:$PATH' >> $BASH_ENV
      - run:
          command: |
            pip install --user pipenv virtualenv
            which pipenv
            python --version
            pipenv --version
            pipenv install
            pipenv run pytest --version
